defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

wandb:
  project: "calm-pde"
  entity: "calm-pde"

experiment:
  name: "CALM-PDE-1D"
  model_name: "CALM_PDE_Burgers"
  model_tag: ""
  random_seed: 3407

  # Model configuration
  training_type: "rollout"
  neural_ode_model_class: "NeuralODE"
  dropout: 0.0
  optimizer: "adamw"
  loss_fn: "rel_l2"
  scheduler: "cosine"
  scheduler_warump_fraction: 0.2
  batch_size: 64
  epochs: 500
  learning_rate: 1.e-3

  # Data configuration
  dataset: "PDEBenchBurgers"
  data_path: "{LOCAL_DIR}/pdebench_datasets/"
  data_file: "1D_Burgers_Sols_Nu0.001.hdf5"
  rollout_steps: 40
  reduced_resolution: 1
  reduced_resolution_t: 5
  truncated_trajectory_length: -1
  reduced_batch: 1
  num_workers: 2