defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

wandb:
  project: "calm-pde"
  entity: "calm-pde"

experiment:
  name: "CALM-PDE-Airfoil"
  model_name: "CALM_PDE_Airfoil"
  model_tag: ""
  random_seed: 3407

  # Model configuration
  training_type: "rollout"
  neural_ode_model_class: "NeuralODE"
  dropout: 0.0
  optimizer: "adamw"
  loss_fn: "rel_l2"
  scheduler: "cosine"
  scheduler_warumup_fraction: 0.2
  batch_size: 16
  epochs: 500
  learning_rate: 6.e-4

  # Data configuration
  dataset: "AirfoilTime"
  data_path: "{LOCAL_DIR}/meshgraphnets_datasets/airfoil/"
  data_file: "airfoil"
  rollout_steps: 15
  reduced_resolution: 1
  reduced_resolution_t: 2
  truncated_trajectory_length: -1
  reduced_batch: 1
  num_workers: 2