defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

wandb:
  project: "calm-pde"
  entity: "calm-pde"

experiment:
  name: "CALM-PDE-Cylinder"
  model_name: "CALM_PDE_Cylinder"
  model_tag: ""
  random_seed: 3407

  # Model configuration
  training_type: "rollout"

  neural_ode_model_class: "NeuralODE"
  dropout: 0.0
  optimizer: "adamw"
  loss_fn: "rel_l2"
  scheduler: "cosine"
  scheduler_warmup_fraction: 0.2
  batch_size: 8
  epochs: 500
  learning_rate: 1.e-3

  # Data configuration
  dataset: "CylinderTime"
  data_path: "{LOCAL_DIR}/meshgraphnets_datasets/cylinder_flow/"
  data_file: "cylinder"
  rollout_steps: 14
  reduced_resolution: 1
  reduced_resolution_t: 2
  truncated_trajectory_length: -1
  reduced_batch: 1
  num_workers: 2
