defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

wandb:
  project: "calm-pde"
  entity: "calm-pde"

experiment:
  name: "CALM-PDE-3D"
  model_name: "CALM_PDE_3D"
  model_tag: ""
  random_seed: 3407
  
  # Model configuration
  training_type: "rollout"
  neural_ode_model_class: "NeuralODE"
  dropout: 0.0
  optimizer: "adamw"
  loss_fn: "rel_l2"
  scheduler: "cosine"
  scheudler_warmup_fraction: 0.2
  batch_size: 4
  epochs: 500
  learning_rate: 1.e-4

  # Data configuration
  dataset: "PDEBenchCNS"
  data_path: "{LOCAL_DIR}/pdebench_datasets/"
  data_file: "3D_CFD_Rand_M1.0_Eta1e-08_Zeta1e-08_periodic_Train.hdf5"
  rollout_steps: 20
  reduced_resolution: 2
  reduced_resolution_t: 1
  truncated_trajectory_length: 21
  reduced_batch: 1
  num_workers: 2